version: '3.6'
services:
  edgeware_mainnet:
    image: eteissonniere/edgeware:latest
    logging:
      driver: "json-file"
      options:
        max-size: "100M"
        max-file: "2"
    volumes:
      - ./data_edg_mainnet:/data/chains
    ports:
      - "127.0.0.1:9933:9933"
      - "0.0.0.0:9944:9944"
      - "127.0.0.1:30333:30333"
    command: ['--chain','edgeware','--name', 'substrate_playground', '--ws-external', '--rpc-cors','all' ]
